site_name: Poshmark -Assingment 

nav :
  - Home: 'index.md'
  - Exploratory data Analysis: 'eda.md'
  - Modeling: 'modeling.md'
  - Feature Selection: 'feat_sel.md'
  - Deployment: 'deployment.md'
  - Hyperameter_tuning: 'hyperameter_tuning.md'
  - Explanation: 'explanation.md'
theme:
  name: 'material'
